name: m3u8_player_plus
description: An enhanced Flutter package that provides a customizable M3U8 player for mobile and web platforms with improved mobile support and modern web APIs.
version: 1.0.1
homepage:
repository: https://github.com/dhiaCodes/m3u8_player
topics:
  - video
  - video-player
  - m3u8

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.5.0
  video_player: ^2.8.1
  wakelock_plus: ^1.2.10
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1